### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by s8321414** [dimkard/distrowatcher#1]
I install this applet on Chakra GNU/Linux, and I install all its dependencies, it can compile, but it doesn't work, it told me I have lacked some package, but I already install all dependencies...

**Comment by s8321414** [comment]
Plasma 5 version here.

**Comment by dimkard** [comment]
After compilation, is it the installation that fails? Or you can install but it says something like the below in the widget window?

An error has occurred initializing the widget. Check documentation and ensure that all the required packages have been installed

If this is the case, may you please execute the command: 
plasmawindowed org.kde.distrowatcher 
and send the results?

I also need the exact plasma version you run.

**Comment by s8321414** [comment]
Yes, it show "An error has occurred initializing the widget. Check documentation and ensure that all the required packages have been installed" in applet.
If I run "plasmawindowed org.kde.distrowatcher" in konsole, it will shows the same error in applet, and shows following messages in konsole:
<code>[jeff@chakrapc ~](21:51:28)$ plasmawindowed org.kde.distrowatcher
unversioned plugin detected, may result in instability
unversioned plugin detected, may result in instability
requesting config for "散佈版觀察家" without a containment!
couldn't create slave: "無法建立 io-slave:\nklauncher 回應: 不明的協定‘plasmapackage’。\n"
file:///usr/share/plasma/plasmoids/org.kde.distrowatcher/contents/ui/VerticalLayout.qml:24:1: Script plasmapackage:/ui/js/style.js unavailable
plasmapackage:/ui/js/style.js: Network error
qml: DW: Error Loading tabButAndGroup</code>
I am on Plasma 5.4.2

**Comment by dimkard** [comment]
May you pull the new development snapshot and try again?

**Comment by s8321414** [comment]
@dimkard If I run <code>plasmawindowed org.kde.distrowatcher</code>, it can work, but wtill not in workspace...

**Comment by s8321414** [comment]
and have some many messages shown in konsole:
unversioned plugin detected, may result in instability
unversioned plugin detected, may result in instability
requesting config for "散佈版觀察家" without a containment!
Failed to register Notifications service
Overwriting existing old cached entry due to collision.
Overwriting existing old cached entry due to collision.
Overwriting existing old cached entry due to collision.
<Unknown File>: QML : Binding loop detected for property "rightMargin"
Could not resolve property : linearGradient5334
Could not resolve property : linearGradient5332
Could not resolve property : linearGradient5326
Could not resolve property : linearGradient5328
Could not resolve property : linearGradient5334
Could not resolve property : linearGradient5332
Could not resolve property : linearGradient5326
Could not resolve property : linearGradient5328
Could not resolve property : linearGradient5334
Could not resolve property : linearGradient5332
Could not resolve property : linearGradient5326
Could not resolve property : linearGradient5328
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::save: Painter not active
QPainter::translate: Painter not active
QPainter::scale: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::opacity: Painter not active
QPainter::brush: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::drawPath: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawPath: Painter not active
QPainter::setBrush: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::opacity: Painter not active
QPainter::brush: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::drawPath: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawPath: Painter not active
QPainter::setBrush: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::end: Painter not active, aborted
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::save: Painter not active
QPainter::translate: Painter not active
QPainter::scale: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::opacity: Painter not active
QPainter::brush: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::drawPath: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawPath: Painter not active
QPainter::setBrush: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::opacity: Painter not active
QPainter::brush: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::drawPath: Painter not active
QPainter::setPen: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawPath: Painter not active
QPainter::setBrush: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::end: Painter not active, aborted
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0

**Comment by dimkard** [comment]
Regarding "If I run plasmawindowed org.kde.distrowatcher, it can work, but wtill not in workspace...".

I think that the workspace uses the cached old version. If you remove the widget from the panel/desktop, logout-login and add it again it should work...

**Comment by s8321414** [comment]
@dimkard ah yeah, it works fine now using latest git version, thanks!

**Comment by s8321414** [comment]
I think this issue could be closed, but I am wondering why configuration diglog is all English here...
